name: Splatoon3 Send DropBox

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACC_LOC: ${{ secrets.ACC_LOC }}
      GTOKEN: ${{ secrets.GTOKEN }}
      BULLETTOKEN: ${{ secrets.BULLETTOKEN }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      F_GEN: ${{ secrets.F_GEN }}
      D_API_KEY: ${{ secrets.D_API_KEY }}
      D_APP_SECRET: ${{ secrets.D_APP_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      
    name: Splatoon3 Send DropBox
    steps:
      - uses: actions/checkout@v3
      - name: Get DropBox Token
        run: |
          DTOKEN=$(curl -s https://api.dropbox.com/oauth2/token \
          -d grant_type=refresh_token \
          -d refresh_token="${{ env.REFRESH_TOKEN }}" \
          -u ${{ env.D_API_KEY }}:${{ env.D_APP_SECRET }} | jq -r ".access_token")
          echo "DTOKEN=$DTOKEN" >> $GITHUB_ENV

# echo "::add-mask::$DTOKEN"
# echo "DTOKEN=$DTOKEN" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'kkchn0am/s3s-to-statink2'
          
      - name: Splatoon3 Send DropBox
        run: |
          echo test
          echo ${{ env.DTOKEN }}
          pwd
          ls -l
          curl -X POST https://content.dropboxapi.com/2/files/upload \
            --header "Authorization: Bearer ${{ env.DTOKEN }}" \
            --header "Dropbox-API-Arg: {\"path\":\"log.txt\"}" \
            --header  "Content-Type: application/octet-stream" \
            --data-binary @log.txt
