name: Splatoon3 Battlelog Uplorder

on:
  schedule:
    - cron: '0 0-23/3 * * *'
  workflow_dispatch:
  
permissions: # ログファイル修正のため権限を設定
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACC_LOC: ${{ secrets.ACC_LOC }}
      GTOKEN: ${{ secrets.GTOKEN }}
      BULLETTOKEN: ${{ secrets.BULLETTOKEN }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      F_GEN: ${{ secrets.F_GEN }}

    name: Splatoon3 Battlelog Uploader
    steps:
      - uses: actions/checkout@v4
      - name: Commit & Push # ログファイルをプッシュしてリポジトリに反映
        env:
          TZ: 'Asia/Tokyo'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          echo -e $(date +'%Y-%m-%d %H:%M:%S') > log.txt
          git add log.txt
          git commit -m "Botによるコミット"
          git push origin main
          
      - name: Set up Python 3.11 # Pythonのセットアップ
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Checkout frozenpandaman/s3s # s3sをチェックアウト
        uses: actions/checkout@v4
        with:
          repository: 'frozenpandaman/s3s'
          path: s3s

      - name: Generate config.txt # config.txtの作成
        working-directory: s3s
        run: |
          echo '{"api_key": "${{ env.API_KEY }}", "acc_loc": "${{ env.ACC_LOC }}", "gtoken": "${{ env.GTOKEN }}", "bullettoken": "${{ env.BULLETTOKEN }}", "session_token": "${{ env.SESSION_TOKEN }}", "f_gen": "${{ env.F_GEN }}" }' > config.txt
          cat config.txt
          
      - name: Install s3s requirements # s3sのパッケージリストを取得
        working-directory: s3s
        run: |
          pip install -r requirements.txt
          
      - name: Run s3s # s3sの実行
        working-directory: s3s
        run: |
          python3 s3s.py -r
