name: Splatoon3 Send DropBox

on:
  workflow_dispatch:
  
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ACC_LOC: ${{ secrets.ACC_LOC }}
      GTOKEN: ${{ secrets.GTOKEN }}
      BULLETTOKEN: ${{ secrets.BULLETTOKEN }}
      SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
      F_GEN: ${{ secrets.F_GEN }}
      D_API_KEY: ${{ secrets.D_API_KEY }}
      D_APP_SECRET: ${{ secrets.APP_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      
    name: Splatoon3 Send DropBox
    steps:
      - uses: actions/checkout@v3
      - name: Get DropBox Token
        run: |
          echo $(curl -s https://api.dropbox.com/oauth2/token -d grant_type=refresh_token -d refresh_token=\"$REFRESH_TOKEN\" -u $D_API_KEY:$D_APP_SECRET | jq -r ".access_token")

# echo "::add-mask::$DTOKEN"
# echo "DTOKEN=$DTOKEN" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: 'kkchn0am/s3s-to-statink2'
          
      - name: Splatoon3 Send DropBox
        working-directory: /
        run: |
          echo test
          echo "${{ env.DTOKEN }}"
          echo test
          ls -lR
          curl -X POST -f -H "Authorization: Bearer ${{ env.DTOKEN }}" \
          -D - -H "Dropbox-API-Arg: {\"path\": \"/log.txt\",\"mode\": \"overwrite\",\"mute\": false}" \
          -H "Content-Type: application/octet-stream" \
          --data-binary @/log.txt \
          https://content.dropboxapi.com/2/files/upload
